#!/bin/bash
#grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd.log > /Path/ToThe/IP_List

#create files
touch IP_List && touch IP_List_Dedup
touch IP_List_Final && touch IP_List_Sources
touch IP_List_Rex

#pull IPs with grep and regex
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd* >> IP_List
#grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd.log.2 >> IP_List
#grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd.log.3 >> IP_List
#grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd.log.4 >> IP_List
#grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" splunkd.log.5 >> IP_List

#sort list and dedup
sort IP_List | uniq >> IP_List_Dedup
sort IP_List_Dedup | uniq > IP_List_Sources
grep -E -o "([0-9]{1,3}[\.]){3}[0-9]{1,3}" IP_List_Sources > IP_List_Rex
sort -u IP_List_Rex > IP_List_Final
